const fs = require('fs-extra');
const path = require('path');

// Define paths
const publicDir = path.join(__dirname, 'public');
const buildDir = path.join(__dirname, 'build');

// Function to copy public assets to build directory
async function copyPublicAssets() {
  try {
    // Ensure build directory exists
    await fs.ensureDir(buildDir);
    
    // Copy all files from public to build
    console.log('Copying public assets to build directory...');
    await fs.copy(publicDir, buildDir, {
      filter: (src) => {
        // Don't copy index.html as it will be generated by React
        return path.basename(src) !== 'index.html';
      }
    });
    
    console.log('Public assets copied successfully!');
  } catch (err) {
    console.error('Error copying public assets:', err);
    process.exit(1);
  }
}

// Run the copy function
copyPublicAssets();
