const fs = require('fs-extra');
const path = require('path');

// Define paths
const publicDir = path.join(__dirname, 'public');
const buildDir = path.join(__dirname, 'build');
const srcDir = path.join(__dirname, 'src');

// Function to copy public assets to build directory
async function copyPublicAssets() {
  try {
    // Ensure build directory exists
    await fs.ensureDir(buildDir);
    
    // Copy all files from public to build
    console.log('Copying public assets to build directory...');
    await fs.copy(publicDir, buildDir, {
      filter: (src) => {
        // Don't copy index.html as it will be generated by React
        return path.basename(src) !== 'index.html';
      }
    });
    
    // Create assets directory in build if it doesn't exist
    const buildAssetsDir = path.join(buildDir, 'assets');
    await fs.ensureDir(buildAssetsDir);
    
    // Copy any assets from src/assets if it exists
    const srcAssetsDir = path.join(srcDir, 'assets');
    if (fs.existsSync(srcAssetsDir)) {
      console.log('Copying src/assets to build/assets...');
      await fs.copy(srcAssetsDir, buildAssetsDir);
    }
    
    // Create an empty .nojekyll file to prevent GitHub Pages from using Jekyll
    await fs.writeFile(path.join(buildDir, '.nojekyll'), '');
    
    console.log('All assets copied successfully!');
  } catch (err) {
    console.error('Error copying assets:', err);
    process.exit(1);
  }
}

// Run the copy function
copyPublicAssets();
