services:
  # Frontend service (React app)
  - type: web
    name: zynith-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_PROD_API_URL
        fromService:
          name: zynith-api
          type: web
          property: url
        postfix: /api

  # Backend service (Express API)
  - type: web
    name: zynith-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false # User needs to set this in the Render dashboard
      - key: JWT_SECRET
        generateValue: true # Automatically generates a secure value
